### ISSUE TITLE
first run bug

### ISSUE THREAD

**Issue by FelipeMartini** [vumik/docker-harbor#1]
(5/6) Installing re2c (1.3-r1)
(6/6) Installing .phpize-deps-configure (20200430.190317)
Executing busybox-1.31.1-r9.trigger
OK: 248 MiB in 80 packages
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
configure: error: unrecognized options: --with-freetype-dir, --with-jpeg-dir, --with-png-dir
Service 'php-cli' failed to build: The command '/bin/sh -c apk upgrade --update && apk add 		bash 		autoconf 		g++         make 	    cyrus-sasl-dev         gmp-dev 	    freetype-dev 	    libpng-dev 	    libjpeg-turbo-dev 		postgresql-dev 	    libmemcached-dev         libzip-dev         oniguruma-dev     && docker-php-ext-configure         gd --with-freetype-dir=/usr/include/            --with-jpeg-dir=/usr/include/            --with-png-dir=/usr/include     && docker-php-ext-install         gd mbstring zip iconv pdo_mysql pdo_pgsql bcmath     && pecl download memcached 	&& tar -xf memcached-* 	&& ( 		cd memcached-3.1.5 		&& phpize 		&& ./configure --disable-memcached-sasl 		&& make 		&& make install 	) 	&& rm -r memcached-3.1.5 	&& docker-php-ext-enable memcached     && pecl download xdebug 	&& tar -xf xdebug-* 	&& ( 		cd xdebug-* 		&& phpize 		&& ./configure 		&& make 		&& make install 	) 	&& rm -r xdebug-* 	&& docker-php-ext-enable xdebug     && pecl download redis 	&& tar -xf redis-* 	&& ( 		cd redis-* 		&& phpize 		&& ./configure 		&& make 		&& make install 	) 	&& rm -r redis-* 	&& docker-php-ext-enable redis     && curl -L https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz >> ./libmaxminddb-1.2.0.tar.gz     && tar -xf libmaxminddb-1.2.0.tar.gz     && (    		cd libmaxminddb*     	&& ./configure     	&& make     	&& make install     )     && rm -r libmaxminddb*     && curl -L https://github.com/maxmind/MaxMind-DB-Reader-php/archive/v1.1.0.tar.gz >> ./MaxMind-DB-Reader-php-1.1.0.tar.gz     && tar -xf MaxMind-DB-Reader-php-1.1.0.tar.gz     && (         cd MaxMind-DB-Reader-php-*/ext         && cp /usr/local/include/maxminddb.h ./maxminddb.h         && cp /usr/local/include/maxminddb_config.h ./maxminddb_config.h         && phpize         && ./configure         && make         && make install     )     && rm -r MaxMind-DB-Reader*     && docker-php-ext-enable maxminddb     && curl -L http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz >> GeoLite2-City.mmdb.gz     && curl -L http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz >> GeoLite2-Country.mmdb.gz     && gunzip GeoLite2-City.mmdb.gz     && gunzip GeoLite2-Country.mmdb.gz     && mkdir /usr/local/share/GeoIP     && mv GeoLite2-City.mmdb /usr/local/share/GeoIP     && mv GeoLite2-Country.mmdb /usr/local/share/GeoIP 	&& rm -rf /var/cache/apk/*    && mkdir -p /srv/www/html' returned a non-zero code: 1
Failed to deploy 'Compose: docker-compose.y

**Comment by vumik** [comment]
Hi!
Yeah, MaxMind GeoIP database isn't public now =(
You should use different GeoIP database or service because MaxMind GeoIP database has been removed from the project.

Please, pull updates and try building images again.
