### ISSUE TITLE
yat error at php 7.4

### ISSUE THREAD

**Issue by FelipeMartini** [vumik/docker-harbor#2]
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
configure: error: unrecognized options: --with-freetype-dir, --with-jpeg-dir, --with-png-dir
Service 'php-cli' failed to build: The command '/bin/sh -c apk upgrade --update && apk add 		bash 		autoconf 		g++         make 	    cyrus-sasl-dev         gmp-dev 	    freetype-dev 	    libpng-dev 	    libjpeg-turbo-dev 		postgresql-dev 	    libmemcached-dev         libzip-dev         oniguruma-dev     && docker-php-ext-configure         gd --with-freetype-dir=/usr/include/            --with-jpeg-dir=/usr/include/            --with-png-dir=/usr/include     && docker-php-ext-install         gd mbstring zip iconv pdo_mysql pdo_pgsql bcmath     && pecl download memcached 	&& tar -xf memcached-* 	&& ( 		cd memcached-3.1.5 		&& phpize 		&& ./configure --disable-memcached-sasl 		&& make 		&& make install 	) 	&& rm -r memcached-3.1.5 	&& docker-php-ext-enable memcached     && pecl download xdebug 	&& tar -xf xdebug-* 	&& ( 		cd xdebug-* 		&& phpize 		&& ./configure 		&& make 		&& make install 	) 	&& rm -r xdebug-* 	&& docker-php-ext-enable xdebug     && pecl download redis 	&& tar -xf redis-* 	&& ( 		cd redis-* 		&& phpize 		&& ./configure 		&& make 		&& make install 	) 	&& rm -r redis-* 	&& docker-php-ext-enable redis 	&& rm -rf /var/cache/apk/*    && mkdir -p /srv/www/html' returned a non-zero code: 1
Failed to deploy 'Compose: docker-compose.yml': `docker-compose` process finished with exit code 1

**Comment by vumik** [comment]
This one issue has been fixed too)
Please, pull updates and try building images again.
