### ISSUE TITLE
now i think running ok

### ISSUE THREAD

**Issue by FelipeMartini** [vumik/docker-harbor#3]
now have finish the compiling, but the php-cli container not keep runing this is normal? run and terminated at end point? also where i can acess the harbor page? on localhost only see nginx default page, also where are the default harbor registry admin password?

Also thanks for your replys.

**Comment by vumik** [comment]
1. Yes it's normal for php-cli container. You need use php-cli container for commands in console or with IDE tools.

2. Right.  You can access to your application on localhost.

3. You are set all configs (and passwords) in env file before run `docker-compose up`

**Comment by FelipeMartini** [comment]
O seted my .env but localhost only showme a nginx default page, maybe i do something wrong? No have more errors 

![image](https://user-images.githubusercontent.com/53950843/81089994-79be9c00-8ed3-11ea-8b4f-b110cd94302a.jpg)

**Comment by vumik** [comment]
Please, pull updates and try building images again.
I've just added one more fix.

Although, I think this fix not about your problem with nginx default page, but maybe it will help.

**Comment by FelipeMartini** [comment]
it compile fine again but yet i only see nginx default page at localhost.


Status: Downloaded newer image for rabbitmq:3.7-alpine
Building php-fpm
[WARNING]: Empty continuation line found in:
    RUN apk upgrade --update && apk add                 bash            autoconf                g++         make
            cyrus-sasl-dev         gmp-dev          freetype-dev            libpng-dev      libjpeg-turbo-dev       libxpm-dev      libwebp-dev                 postgresql-dev      libmemcached-dev         libzip-dev         oniguruma-dev     && docker-php-ext-configure         gd --enable-gd                     --with-webp                     --with-jpeg                     --with-xpm                      --with-freetype          && docker-php-ext-install           gd mbstring zip iconv pdo_mysql pdo_pgsql bcmath     && pecl download memcached   && tar -xf memcached-*  && (            cd memcached-3.1.5              && phpize               && ./configure --disable-memcached-sasl                 && make
                && make install         )       && rm -r memcached-3.1.5        && docker-php-ext-enable memcached     && pecl download xdebug  && tar -xf xdebug-*     && (            cd xdebug-*             && phpize               && ./configure          && make                 && make install         )       && rm -r xdebug-*       && docker-php-ext-enable xdebug     && pecl download redis      && tar -xf redis-*      && (            cd redis-*              && phpize
                && ./configure          && make                 && make install         )       && rm -r redis-*
        && docker-php-ext-enable redis  && rm -rf /var/cache/apk/*    && mkdir -p /srv/www/html
[WARNING]: Empty continuation lines will become errors in a future release.
Step 1/3 : FROM php:7.4-fpm-alpine





also i only have small warnings at compile

warning: mbstring (mbstring.so) is already loaded!


warning: iconv (iconv.so) is already loaded!


checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
./configure: line 1: /usr/bin/file: not found
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes

=====================================================

But i think nothing related with nginx , why it not is taking the configurations? can you help me with that?

**Comment by vumik** [comment]
It isn't a problem with docker-harbor.
I think you have running nginx on localhost.
You need to stop ngnix and try again.
